import type { Metadata } from 'next';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { dir } from 'i18next';
import { languages } from '../i18n/settings';

export async function generateStaticParams() {
    return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    children: React.ReactNode;
    params: {
        lng: string;
    };
}

export default async function RootLayout({
    children,
    params: { lng },
}: RootLayoutProps) {
    return (
        <html lang={lng} dir={dir(lng)}>
            <head />
            <body className="antialiased bg-background">
                <ToastContainer />
                <main>{children}</main>
            </body>
        </html>
    );
}
