import type { Metadata } from 'next';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    children: React.ReactNode;
    params: {
        lng: string;
    };
}

export default async function RootLayout({
    children,
    params: { lng },
}: RootLayoutProps) {
    const messages = await getMessages();
    return (
        <html lang={lng}>
            <head />
            <body className="antialiased bg-background">
                <ToastContainer />
                <NextIntlClientProvider messages={messages}>
                    {children}
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
